# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoValet < Formula
  desc "A Laravel Valet clone for Go"
  homepage "https://github.com/arifnurulhakim/go-valet"
  version "0.0.7"
  license "MIT"

  depends_on "air"
  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.7/go-valet_Darwin_x86_64.tar.gz"
      sha256 "ec623fcdd398831f51aa7998204a1818428d19fe5bc358333f30bf8d137318f3"

      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.7/go-valet_Darwin_arm64.tar.gz"
      sha256 "ef4fdbaf95458af3eac9846165508d8521f0640a815bb22ae565367d781a6993"

      def install
        bin.install "go-valet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.7/go-valet_Linux_x86_64.tar.gz"
      sha256 "44d3682446169af264dbccc9087c538619fd97e8894672d13782abed7e899a94"
      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.7/go-valet_Linux_arm64.tar.gz"
      sha256 "365f751a4014f61668ca14904eb9a14e1349782a1f2de701b8a3d2ce5bf234c8"
      def install
        bin.install "go-valet"
      end
    end
  end

  service do
    run [opt_bin/"go-valet", "daemon", "start"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/go-valet.log"
    error_log_path var/"log/go-valet.error.log"
  end

  test do
    system "#{bin}/go-valet --version"
  end
end
