# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoValet < Formula
  desc "A Laravel Valet clone for Go"
  homepage "https://github.com/arifnurulhakim/go-valet"
  version "0.0.1"
  license "MIT"

  depends_on "air"
  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.1/go-valet_Darwin_x86_64.tar.gz"
      sha256 "603e0349ba2c215df2256c61388733c4a93ebe657243735232f03370e7c88876"

      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.1/go-valet_Darwin_arm64.tar.gz"
      sha256 "eda7f221cc41c545327f0b5fe220bc2dc7f19ac2b56671c12333dbc00c8b4ea4"

      def install
        bin.install "go-valet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.1/go-valet_Linux_x86_64.tar.gz"
      sha256 "a995a09cca82483da8cfcb0f6e3f31456d106e0c9db2c6146d8deff9addc5202"
      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.1/go-valet_Linux_arm64.tar.gz"
      sha256 "2463ec856b56de3584b2313f5bffd6477336dff5e8415bfe84151dde285b865f"
      def install
        bin.install "go-valet"
      end
    end
  end

  service do
    run [opt_bin/"go-valet", "daemon", "start"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/go-valet.log"
    error_log_path var/"log/go-valet.error.log"
  end

  test do
    system "#{bin}/go-valet --version"
  end
end
