# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoValet < Formula
  desc "A Laravel Valet clone for Go"
  homepage "https://github.com/arifnurulhakim/go-valet"
  version "0.0.4"
  license "MIT"

  depends_on "air"
  depends_on "caddy"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.4/go-valet_Darwin_x86_64.tar.gz"
      sha256 "824e6fb8c5bc9921303728ca7fe5386969889a7c5cb0bb3a26a9df416002e016"

      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.4/go-valet_Darwin_arm64.tar.gz"
      sha256 "e8570d3c025cfb0948a25f8a69dc2ea188499d90e6017c8ff50fe00697731309"

      def install
        bin.install "go-valet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.4/go-valet_Linux_x86_64.tar.gz"
      sha256 "ec748dcf13d3de963e358ee03ec0c19fe0776e23f9a6ec583ce138079a2949d4"
      def install
        bin.install "go-valet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arifnurulhakim/go-valet/releases/download/v0.0.4/go-valet_Linux_arm64.tar.gz"
      sha256 "cff2c4495172214de1f7eafa707e1f4301342cbd98e774f59acf81531b22c45f"
      def install
        bin.install "go-valet"
      end
    end
  end

  service do
    run [opt_bin/"go-valet", "daemon", "start"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/go-valet.log"
    error_log_path var/"log/go-valet.error.log"
  end

  test do
    system "#{bin}/go-valet --version"
  end
end
